### ISSUE TITLE
training detailes for HSD

### ISSUE THREAD

**Issue by tingtingliangvs** [JialeCao001/HSD#1]
Hi there!
Thanks for sharing your code. The idea is great and the code is elegant. I have a few questions about  the hardware setup. How many GPUs do you use for training HSD, on what kind of GPUs? How long does it take to fully train a vgg16_320?

**Comment by JialeCao001** [comment]
Thanks. 4 Telsa V100 GPUs are used for training. I remember that it takes about 4 days for training vgg16_320.
